// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>GreenAPI Test APP | Fedotov Maxim</title><link rel=\"stylesheet\" href=\"/public/style.css\"><script type=\"module\" src=\"/public/datastar.js\"></script></head><body><div style=\"padding-top: 120px;\"><div class=\"container\"><div class=\"wrapper\"><div class=\"left\"><div class=\"settings\"><input type=\"text\" id=\"instanceID\" placeholder=\"instanceID\"> <input type=\"text\" id=\"instanceTokenAPI\" placeholder=\"instanceTokenAPI\"></div><button class=\"getSettingsBtn\">getSettings</button> <button class=\"getInstanceStateBtn\">getInstanceState</button><div class=\"newTextMessageData\"><input type=\"text\" id=\"textMessageChatID\" placeholder=\"chatID\"> <textarea name=\"\" id=\"textMessageText\" placeholder=\"message\"></textarea></div><button class=\"sendTextMessageBtn\">sendTextMessage</button><div class=\"newFileUrlMessage\"><input type=\"text\" id=\"fileURLMessageChatID\" placeholder=\"chatID\"> <input type=\"text\" id=\"fileURLMessageURL\" placeholder=\"file url\"> <input type=\"text\" id=\"fileURLMessageFileName\" placeholder=\"file name\"></div><button class=\"sendFileUrlMessageBtn\">sendFileUrlMessage</button></div><div class=\"right\">Ответ:<div id=\"greenteaAPIResponse\"></div></div></div></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
